# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/signs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_available_signs(object):
    def setupUi(self, available_signs):
        available_signs.setObjectName("available_signs")
        available_signs.resize(564, 631)
        self.resources_label = QtWidgets.QLabel(available_signs)
        self.resources_label.setGeometry(QtCore.QRect(50, 530, 441, 71))
        self.resources_label.setObjectName("resources_label")
        self.letters_label = QtWidgets.QLabel(available_signs)
        self.letters_label.setGeometry(QtCore.QRect(60, 30, 171, 471))
        self.letters_label.setObjectName("letters_label")
        self.sign_word_label = QtWidgets.QLabel(available_signs)
        self.sign_word_label.setGeometry(QtCore.QRect(311, 30, 191, 951))
        self.sign_word_label.setObjectName("sign_word_label")

        self.retranslateUi(available_signs)
        QtCore.QMetaObject.connectSlotsByName(available_signs)

    def retranslateUi(self, available_signs):
        _translate = QtCore.QCoreApplication.translate
        available_signs.setWindowTitle(_translate("available_signs", "Let\'s Talk - Available signs"))
        self.resources_label.setText(_translate("available_signs", "TextLabel"))
        self.letters_label.setText(_translate("available_signs", "TextLabel"))
        self.sign_word_label.setText(_translate("available_signs", "TextLabel"))
