# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from re import S
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setGeometry(QtCore.QRect(1291, 36 ,400, 640))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(45, 45, 311, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_last_sign = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_last_sign.setEnabled(True)
        self.button_last_sign.setObjectName("button_last_sign")
        self.verticalLayout.addWidget(self.button_last_sign)
        self.button_duplicate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_duplicate.setObjectName("button_duplicate")
        self.verticalLayout.addWidget(self.button_duplicate)
        self.start_window = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.start_window.setReadOnly(True)
        self.start_window.setObjectName("start_window")
        self.verticalLayout.addWidget(self.start_window)
        
        self.start_window.setPlainText('')
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.button_last_sign.clicked.connect(self.delete_last)

        self.button_duplicate.clicked.connect(self.duplicate_last)

    def delete_last(self):
        from api.webcam_prediction import sentence
        try:
            sentence.pop()
            print('POPed')
        except:
            print('cant pop')

    def duplicate_last(self):
        from api.webcam_prediction import sentence
        try:
            sentence.append(sentence[-1].lower())
        except:
            print('can t append')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Let\'s talk"))
        self.button_last_sign.setText(_translate("Form", "Delete last sign"))
        self.button_duplicate.setText(_translate("Form", "Duplicate last sign"))
